### ISSUE TITLE
Works! Requires some setup

### ISSUE THREAD

**Issue by mikz** [gkpln3/CapsLockNoDelay#1]
Hey. First thank you for this. Much appreciated!

I had to manually add the app to not only the Accessibility but also Input monitoring. Running on Big Sur. 

It might not be obvious for some users they need to do that. There was no pop up for permissions. And also the obvious Shift Right Click and open to avoid Gatekeeper check on the first run.

**Comment by gkpln3** [comment]
Thanks for the input!
I will add it to the readme.
