### ISSUE TITLE
Installation helper

### ISSUE THREAD

**Issue by gkpln3** [gkpln3/CapsLockNoDelay#10]
It would be nice to have a mini installation wizard that will check to see if the application is running from `/Applications`, if not, it would prompt the user to move it there automatically;
Then it would check to see if the app has accessibility permissions, and prompt the user to allow them;
Lastly it will add the app to the user's login item automatically.

Any help with these would be appreciated.

**Comment by XInTheDark** [comment]
Completely agree!
