### ISSUE TITLE
Erratic behaviour when using Caps Lock for input source change

### ISSUE THREAD

**Issue by gbougiakas** [gkpln3/CapsLockNoDelay#11]
Hello, 

I am using caps lock to change typing language (input source) and the lag is driving me crazy so I ended up here. I tried using this app and now I think lag is gone but when hitting caps lock I get both language change and caps lock turning on. Is there maybe something that can be done to use this app while using caps lock to change languages?

**Comment by gkpln3** [comment]
I've just posted a new version that hopes to fix this, can you please check and confirm?

**Comment by gbougiakas** [comment]
Hi, it seems to be working fine! Thanks so much.
