### ISSUE TITLE
Malware alert

### ISSUE THREAD

**Issue by linkin85** [gkpln3/CapsLockNoDelay#12]
Getting this message, executable was downloaded from here.

**“CapsLockNoDelay” will damage your computer. You should move it to the Bin.**

**Comment by gbougiakas** [comment]
same here with latest version

**Comment by gkpln3** [comment]
You probably see this message since apple doesn't know this binary, nor is it signed using official apple developer certificate.
You can bypass this message by selecting "allow software from unidentified developers" in the security and privacy section in system preferences.

If you do not trust this binary to be free of malware, you can download the source code, check that it does only what it claims and build it yourself.

**Comment by gbougiakas** [comment]
Hmm,

there is no such option in Ventura anymore

<img width="475" alt="image" src="https://user-images.githubusercontent.com/3873821/207393474-49643b1c-3b3a-4260-af81-7ac07f62bb83.png">

**Comment by gkpln3** [comment]
Yes sorry, I meant the option you have selected.

**Comment by andromeda-0** [comment]
Hi @gkpln3, thanks for creating this great tool! It has been very helpful.

I am experiencing the same issue, and selecting "Allow applications downloaded from App Store and identified developers" no longer works for me. Are there any workarounds for this?

**Comment by andromeda-0** [comment]
Update: Selecting "override malware protection" in the app info won't work.

**Comment by gbougiakas** [comment]
I second that

**Comment by gkpln3** [comment]
Well this suddenly happens on my machine too, seems like Ventura is doing something special here.
I'm looking into it.

**Comment by andromeda-0** [comment]
I just verified the following works on my machine: 
* Download from source.
* Install xcode.
* Open the project in xcode
* Follow https://stackoverflow.com/a/59315354/20609595 to update the certificate setting.
* Build

There's a bit of overhead, but IMO this great app is worth it.

**Comment by gkpln3** [comment]
Can you try these binaries and tell me if it works for you?
[CapsLockNoDelay.dmg.zip](https://github.com/gkpln3/CapsLockNoDelay/files/10222553/CapsLockNoDelay.dmg.zip)

**Comment by gavingt** [comment]
> Can you try these binaries and tell me if it works for you? [CapsLockNoDelay.dmg.zip](https://github.com/gkpln3/CapsLockNoDelay/files/10222553/CapsLockNoDelay.dmg.zip)

<img width="266" alt="image" src="https://user-images.githubusercontent.com/24281417/207468787-8d8b9651-f4c3-40cf-a134-53234b6223ec.png">

EDIT: But there was a new "Open Anyway" option at the bottom, so I selected it and now it works!:

<img width="706" alt="image" src="https://user-images.githubusercontent.com/24281417/207469166-72c9c5c0-7d79-49be-b13e-07d64a8317b8.png">

**Comment by gkpln3** [comment]
Good, I'm posting this as a new version, hoping it won't be flagged again.
Thanks everyone.
