### ISSUE TITLE
Accessibility permissions

### ISSUE THREAD

**Issue by Baptmix** [gkpln3/CapsLockNoDelay#13]
Hello,

The application still does not work on Ventura 13.0.1. At startup, it is requested that the Accessibility permissions be set. However, when this is the case, there is always the message. I tried a dozen times, in vain.

![image](https://user-images.githubusercontent.com/56630992/207693630-f3f7f406-9b1b-448f-9fb1-c2bd742dd8f7.png)

**Comment by gbougiakas** [comment]
After getting this message you need to go to security and privacy and below
all the categories there will be the name of the app and an open button
next to it. Click open the app will launch and it can also be opened
normally from now on.

**Comment by gkpln3** [comment]
Try removing the app from there and then adding it back again.

**Comment by Baptmix** [comment]
It worked, thank you
