### ISSUE TITLE
Ventura 13.0.1 thinks this is malware

### ISSUE THREAD

**Issue by john-fowler** [gkpln3/CapsLockNoDelay#14]
Just downloaded latest, 1.0.8, and it is still seen as malware:

![image](https://user-images.githubusercontent.com/14206795/207707818-119e0296-3642-4925-bee9-40721eb6cb11.png)

BTW:  THANK YOU!  THANK YOU!  THANK YOU FOR THIS APP!!! The Caps lock delay has been the bane of my existence since I started using macs.

**Comment by gkpln3** [comment]
Haha mine too.
If you see this screen you can go to "privacy settings" and you'll be able to start the app from there.
Lmk if that works for you so I could close this issue

**Comment by john-fowler** [comment]
Doh!  I just saw your comment.  In the past 5 minutes, I downloaded the source code, built the app on my local machine signed to run locally, and then installed it and ran it like that successfully (after setting up the permissions).  I'll reverse course, re-download your dmg and see if I can run it based on your instructions.

**Comment by john-fowler** [comment]
I was able to open the app directly beneath the "Privacy & Security" menu (it had a warning for it).  I made sure the app was added to Accessibility and Login Items.  I then rebooted, and was able to log in without any warnings concerning the app.  I checked via 'ps', and the app was running in the background.

THANKS FOR THE HELP!
