### ISSUE TITLE
Doesn't work on Monterey 12.5.1

### ISSUE THREAD

**Issue by Bogenbai** [gkpln3/CapsLockNoDelay#15]
MacBook Pro (14-inch, 2021)
Chip: Apple M1 Pro
System: MacOS Monterey 12.5.1

Unfortunately the delay has not disappeared.

**Comment by gkpln3** [comment]
Still doesn't work? did you check your accessibility settings?

**Comment by blacksunset** [comment]
+1

**Comment by gkpln3** [comment]
Did you make sure to add the app to the accessibility permissions tab?

**Comment by gkpln3** [comment]
Please refer to the new method in the readme file.
