### ISSUE TITLE
A bit strange that the input method can't work

### ISSUE THREAD

**Issue by lance6716** [gkpln3/CapsLockNoDelay#18]
After I installed it for some minutes, I found that caps lock can trigger IME switching (the icon in top-right corner is changed to Chinese Pinyin), but I can't use Chinese Pinyin because the Pinyin candidate window does not appear. Do I need to provide some log to locate the problem?

Anyway, thanks for this essential tool.

**Comment by dingguo1996** [comment]
I have the same problem. I think it's the macOS version cause it. My macOS is 12.3.1.

**Comment by lance6716** [comment]
> I have the same problem. I think it's the macOS version cause it. My macOS is 12.3.1.

I'm using 13.2.1

**Comment by gkpln3** [comment]
I admit I've never tried it with Chinese, I'll check it.

**Comment by Max-Cheng** [comment]
@lance6716 
After an accidental test, the problem was solved after disabling the following settings.
System Settings -> Keyboard -> Text Input -> Edit... -> All Input Sources -> Turn Off the "Use the 中/英 Key to Switch to and from ABC".

**Comment by lance6716** [comment]
> @lance6716 After an accidental test, the problem was solved after disabling the following settings. System Settings -> Keyboard -> Text Input -> Edit... -> All Input Sources -> Turn Off the "Use the 中/英 Key to Switch to and from ABC".

thanks for reminding me. in this way how can I switch IME?

**Comment by Max-Cheng** [comment]
> > @lance6716 After an accidental test, the problem was solved after disabling the following settings. System Settings -> Keyboard -> Text Input -> Edit... -> All Input Sources -> Turn Off the "Use the 中/英 Key to Switch to and from ABC".
> 
> thanks for reminding me. in this way how can I switch IME?

If you using IME, your should try by yourself. In my case, after disable this option, using PinYin and press Caplock won't switch to abc input source but still can input english

**Comment by gkpln3** [comment]
Please refer to the new method in the readme file.
