### ISSUE TITLE
Does not work when caps lock is binded to something else.

### ISSUE THREAD

**Issue by sealvessel** [gkpln3/CapsLockNoDelay#2]
My caps lock is binded to the control key, while my control key is binded to the caps lock key.
This program assumes that the caps lock key is the control key, thus making the usage of this program useless for people who don't use the default position of the caps lock key.

**Comment by gkpln3** [comment]
Hey, thanks for the issue!
Can you please add some more information about how to recreate the issue?
How is your caps-lock key remapped?

**Comment by elia** [comment]
<img width="780" alt="image" src="https://user-images.githubusercontent.com/1051/129369511-82e1631b-95b1-41d1-a7fb-e264d323e98f.png">
<img width="181" alt="image" src="https://user-images.githubusercontent.com/1051/129369532-d03906f8-0d9d-482e-8131-f2f45b393e15.png">
<img width="780" alt="image" src="https://user-images.githubusercontent.com/1051/129369551-690c378f-296a-4f53-ae3f-fdbb5e408017.png">

**Comment by trombonehero** [comment]
I'm in the same boat: I want to use Caps Lock as Escape (for Vim purposes), but running this program remaps Caps Lock to, well, Caps Lock.

**Comment by gkpln3** [comment]
Just tried this, it seems that if I map caps lock to escape, it doesn't add any delay.
