### ISSUE TITLE
The plugin is being blocked from opening by Apple

### ISSUE THREAD

**Issue by victormoliveira1** [gkpln3/CapsLockNoDelay#20]
## Description of the Issue

The plugin is now being blocked by Apple with the message "CapsLockNoDelay can't be opened because Apple cannot check it for malicious software" when you try to open the application file.

I could get past that following some of the tips detailed [here](https://www.tenorshare.com/mac-os/apple-cannot-check-it-for-malicious-software.html) but I remember that this wasn't happening before.

Is there anything to do, or it's just the result of the signing method?

## Debug Information

MacOS Ventura 13.5 (22G74)
CapsLockNoDelay 1.0.8

**Comment by Papinian** [comment]
Same issue

**Comment by Turbulentarius** [comment]
I found that Karabiner Elements solves the issue with Caps Lock. The most moronic part is that you have to "remap" Caps Lock to itself, and then the delay disappears. Unfortunately Caps Lock is still bugged / delayed at the login screen, since Karabiner element is only started after you login.

**Comment by Papinian** [comment]
> I found that Karabiner Elements solves the issue with Caps Lock. The most moronic part is that you have to "remap" Caps Lock to itself, and then the delay disappears. Unfortunately Caps Lock is still bugged / delayed at the login screen, since Karabiner element is only started after you login.

I'd prefer not to use an app that logs my keystrokes - any possibility to do this via scripting?

**Comment by Turbulentarius** [comment]
> > I found that Karabiner Elements solves the issue with Caps Lock. The most moronic part is that you have to "remap" Caps Lock to itself, and then the delay disappears. Unfortunately Caps Lock is still bugged / delayed at the login screen, since Karabiner element is only started after you login.
> 
> I'd prefer not to use an app that logs my keystrokes - any possibility to do this via scripting?

While a bit off topic, KE is open source, and afaik does not log keystrokes, and even if it did this would not be transmitted. What it does, however, as all such "tools", is listen to your keystrokes – this is a necessity in order to register the fact that E.g. Caps Lock was pressed. On PC this happens silently without the user knowing, but on Mac the program needs permission to do so. Check it out here: https://github.com/pqrs-org/Karabiner-Elements

**Comment by gkpln3** [comment]
I'll post a fix for this issue in a few moments

**Comment by mmatrosov** [comment]
@gkpln3 Any progress on the fix? I see the same issue in macOS Sonoma 14.0. Your tool is our only hope in this crooked world for now 🙏 

<img width="372" alt="image" src="https://github.com/gkpln3/CapsLockNoDelay/assets/3617951/98591fda-24c1-4ed8-941c-f1d7049ea06a">

**Comment by Jamesdrichey** [comment]
@gkpln3 Also experiencing this issue: M2 chip OS 13.5.1 (22G90)

**Comment by mathomp4** [comment]
I wonder if, [like Stretchly](https://github.com/hovancik/stretchly#application-signing), you need to pass in `--no-quarantine` if installing via brew?

**Comment by boramalper** [comment]
@mathomp4 is right, the following works for me

```bash
brew install --cask capslocknodelay --no-quarantine
```

(MacBook Air M1, 2020)

**Comment by Dooruk** [comment]
Is there a non-brew solution for this 😞 ?

**Comment by HenryWu01** [comment]
> Is there a non-brew solution for this 😞 ?

``Right click`` the application and then click ``Open`` the application. This is an universal solution for all macOS application saying ``Apple cannot check it for malicious software``.

**Comment by gkpln3** [comment]
Hey guys! thanks for the comments. 
Please refer to the new method in the readme :)
