### ISSUE TITLE
The plugin now requires Accessibility permission to work

### ISSUE THREAD

**Issue by victormoliveira1** [gkpln3/CapsLockNoDelay#21]
## Description of the Issue

Along with the "Open at Login" and "Input Monitoring", Apple is now asking for Accessibility permission for the plugin to work, which isn't explained in the "Usage" section of the repository README.

This option is located at Privacy & Security > Accessibility.

## Debug Information

MacOS Ventura 13.5 (22G74)
CapsLockNoDelay 1.0.8

**Comment by gkpln3** [comment]
Thanks for the comment!
This is mentioned in the README... are you sure about that?
