### ISSUE TITLE
Built-in alternative

### ISSUE THREAD

**Issue by decodism** [gkpln3/CapsLockNoDelay#22]
To override the caps lock activation delay, execute in a shell, replacing `<delay_in_ms>`:

```
hidutil property --set '{"CapsLockDelayOverride":<delay_in_ms>}'
```

To reset, use `-1`.

**Comment by gkpln3** [comment]
Wow, it actually works, thanks!

**Comment by HenryWu01** [comment]
I found an issue, after reboot macOS, this value seems to be reseted. I'm running ``macOS Sonoma 14.5``.

```
henry@Henrys-Mac-mini test % hidutil property --get "CapsLockDelayOverride"
(null)
henry@Henrys-Mac-mini test % sudo hidutil property --set '{"CapsLockDelayOverride":0}'
Password:
CapsLockDelayOverride:0
henry@Henrys-Mac-mini test % hidutil property --get "CapsLockDelayOverride"
0
```

**Comment by sealvessel** [comment]
Last login: Mon Sep  2 10:44:47 on ttys000
quark@Sphere-space ~ % hidutil property --set '{"CapsLockDelayOverride":0}'
CapsLockDelayOverride:0
quark@Sphere-space ~ % vim ~/Library/LaunchAgents/local.hidutilKeyMapping.plist

[No write since last change]

Press ENTER or type command to continue
[No write since last change]

Press ENTER or type command to continue













<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>local.hidutilKeyMapping</string>

    <key>ProgramArguments</key>
    <array>
        <string>/usr/bin/hidutil</string>
        <string>property</string>
        <string>--set</string>
        <string>{
            "UserKeyMapping": [
                {   
                "CapsLockDelayOverride": 0
                },
            ]
        }</string>
    </array>

    <key>RunAtLoad</key>

**Comment by sealvessel** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>local.hidutilKeyMapping</string>
    
    <key>ProgramArguments</key>
    <array>
        <string>/usr/bin/hidutil</string>
        <string>property</string>
        <string>--set</string>
        <string>{
            "UserKeyMapping": [
                { 
		"CapsLockDelayOverride": 0
                },
            ]
        }</string>
    </array>
 
    <key>RunAtLoad</key>
    <true/>
</dict>
</plist>

```

**Comment by vorpal56** [comment]
The above comment might be (or is a?) reference to https://superuser.com/a/1858081:

> Save the following to ~/Library/LaunchAgents/local.removecapslockdelay.plist:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>local.removecapslockdelay</string>

    <key>ProgramArguments</key>
    <array>
        <string>/usr/bin/hidutil</string>
        <string>property</string>
        <string>--set</string>
        <string>{"CapsLockDelayOverride":0}</string>
    </array>

    <key>RunAtLoad</key>
    <true/>
</dict>
</plist>
```
> Restart the Mac.
> Note that this doesn't apply the fix to the login screen; it only works after logging in.
