### ISSUE TITLE
Is this working for Big Sur 11.3?

### ISSUE THREAD

**Issue by Valachio** [gkpln3/CapsLockNoDelay#5]
I followed the instructions and copied the file to /applications.  It's showing up in my applications.  

I looked under Accessibility and Input Monitoring under Security & Privacy and the app isn't listed there.

Am I doing something wrong or is it broken for 11.3?

**Comment by gkpln3** [comment]
It should work, I'd bet the reason you don't see this in the accessibility menu since you've yet to run the program.
Try running it and see if it appears.

**Comment by ndom91** [comment]
Could not get it to run in BigSur. I manually added it to the Accessibility section with the little "+" icon. Then the app started at least (visible in Activity Monitor).

However, I was still not able to get rid of the delay this way. Whether with caps lock mapped as default, caps lock mapped to esc in the keyboard system prefs, nor with Karabiner elements.
