### ISSUE TITLE
Can't run app

### ISSUE THREAD

**Issue by Aransh** [gkpln3/CapsLockNoDelay#6]
Was super happy to find someone made this app, but unfortunately it doesn't work for me...
M1 Macbook Pro on MacOS 11.5, I tried both downloading and compiling myself.

After moving the .app into the /Applications directory, and trying multiple times to open the app, I can't see it in the "Security & Privacy" settings, and not in Activity Monitor.

Any idea what could be the issue? let me know if there's any way I can help find it

**Comment by gkpln3** [comment]
Can you try running the app through the terminal and tell me if there's any output?

**Comment by Aransh** [comment]
@gkpln3 yup tried that already, no output.
It did make it appear in the Activity Monitor for a few seconds but then it disappeared

**Comment by gkpln3** [comment]
Are there any crash reports in crashdump? (You can find them under Console.app)

**Comment by Aransh** [comment]
@gkpln3 nope, empty

**Comment by codeHusky** [comment]
@Aransh  You need to follow the steps in the README (hit the + in the accessibility options to add it to the list) to allow the app to run w/out crashing.

**Comment by Aransh** [comment]
@codeHusky Hey, I did follow the README, that's what I'm saying.
The readme says:
Go to System Preferences -> Security & Privacy -> Privacy -> Accessability -> Check CapsLockNoDelay.app -> Input Monitoring -> Check CapsLockNoDelay.app (if present).

I know it states only if present, but I can't see CapsLockNoDelay there, or even in the activity monitor... even after adding to the login items

**Comment by codeHusky** [comment]
@Aransh No you need to add it to the accessibility list via the + in that menu. It will not appear there automatically.

**Comment by gkpln3** [comment]
I suspect this might be related to app sandboxing on M1.
Can you please try the attached version and tell me if it works?
[CapsLockNoDelay.app.zip](https://github.com/gkpln3/CapsLockNoDelay/files/7519818/CapsLockNoDelay.app.zip)

**Comment by codeHusky** [comment]
Just noting here that I was able to get this to work on the M1 by simply manually adding it to the accessibility list, but I do have some concern about power draw in the background since it's not natively built. I'll probably build it on my own soon here

**Comment by gkpln3** [comment]
It is natively compiled for M1, its a [universal binary](https://en.wikipedia.org/wiki/Universal_binary).

**Comment by codeHusky** [comment]
I see, my bad

**Comment by Aransh** [comment]
> I suspect this might be related to app sandboxing on M1.
> Can you please try the attached version and tell me if it works?
> [CapsLockNoDelay.app.zip](https://github.com/gkpln3/CapsLockNoDelay/files/7519818/CapsLockNoDelay.app.zip)

This works! thanks a lot

**Comment by gkpln3** [comment]
Great! I will post a new release, thanks!
