### ISSUE TITLE
cannot open application

### ISSUE THREAD

**Issue by XInTheDark** [gkpln3/CapsLockNoDelay#8]
My Mac identifies the app as malware and cannot let me open it even after I override the malware warning.

**Comment by edsonbittencourt** [comment]
/2

**Comment by gkpln3** [comment]
Looking into it...

**Comment by jellynip** [comment]
me too,

**Comment by gkpln3** [comment]
Can you guys try again with this binary and tell me if it works?
[CapsLockNoDelay.app.zip](https://github.com/gkpln3/CapsLockNoDelay/files/8956080/CapsLockNoDelay.app.zip)

**Comment by edsonbittencourt** [comment]
It's working. Thanks a lot, great job.

**Comment by XInTheDark** [comment]
Working :) Thanks for the app!
