### ISSUE TITLE
[Suggestion] Add an icon for the app

### ISSUE THREAD

**Issue by XInTheDark** [gkpln3/CapsLockNoDelay#9]
The app has no icon right now, it would be great if an icon could be added to make it look better.
Maybe like this ![image](https://user-images.githubusercontent.com/61100393/175245534-7c764a5c-adab-4109-8315-187e0586afd0.png)
or this? ![Unknown](https://user-images.githubusercontent.com/61100393/175245577-3bd1ab9d-6318-4e67-8da3-412f34e7dda8.png)

**Comment by gkpln3** [comment]
I'd love to have an icon.
I suck at designing.
Do you have some more designs? something more round maybe.
Also, I need something original without copyright.

**Comment by XInTheDark** [comment]
> Do you have some more designs? something more round maybe.
> Also, I need something original without copyright.

I'm not really good at designing either -- but I have some friends who could design logos. I'll ask them to help :)

**Comment by XInTheDark** [comment]
@gkpln3 Looks like my friend is busy, so I designed one myself, its 1024x1024px
Idk if you like it 😂 this was my best attempt but it's not that good

![CapsLockNoDelay_logoV1](https://user-images.githubusercontent.com/61100393/175539096-14776891-bd9e-4ecb-a48e-71fd5ffc34cc.png)

**Comment by XInTheDark** [comment]
@gkpln3 Looks like my friend is busy, so I designed one myself, its 1024x1024px
Idk if you like it 😂 this was my best attempt but it's not that good
![CapsLockNoDelay_logoV1](https://user-images.githubusercontent.com/61100393/175539917-7c638828-dbad-48bf-8bf0-eef927e236c3.png)

_edit: re-uploaded cuz the original one sucked_

**Comment by XInTheDark** [comment]
Also, it would be nice if you could add a user interface to the app since the current app shows nothing when run. The UI could be used to quit the app, change settings, show info, update, etc.

**Comment by XInTheDark** [comment]
@gkpln3 added rounded corners since it would look nicer
![CapsLockNoDelay_logoV2_1](https://user-images.githubusercontent.com/61100393/175766057-d783b4fd-e51a-4514-b0f6-ab18112b2f59.png)

_edit: resized_

**Comment by XInTheDark** [comment]
It has a transparent background by the way - I tried using it as the app icon and it looks okay.
_app icon preview:_ <img width="221" alt="App icon preview" src="https://user-images.githubusercontent.com/61100393/175766182-c5cb74ad-8d35-443b-8a78-91690ce27907.png">

**Comment by gkpln3** [comment]
This looks cool, maybe just add a small background gradient (bright at the top, dark at the bottom), and send me the png file here?

**Comment by XInTheDark** [comment]
Here :)

![CapsLockNoDelay_logoV3](https://user-images.githubusercontent.com/61100393/176619564-b7d25bb5-40a2-41bc-8026-32a302cf69c5.png)

**Comment by gkpln3** [comment]
Added in latest release, Thanks! @XInTheDark
